import React from 'react';

export default function ErrorPage () {
    return (
        <div>
        <h1> LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR LOL ERROR </h1>
        </div>
    );
}